import type { QuoteTemplateDefinition } from './types';

/** Plantilla inicial con datos del cliente etiquetados (RNC, dirección, teléfono, etc.). */
export function createDefaultTemplateDefinition(): QuoteTemplateDefinition {
  return {
    version: 1,
    pageWidth: 794,
    pageHeight: 1123,
    elements: [
      {
        id: 'el-logo',
        type: 'companyLogo',
        x: 40,
        y: 36,
        width: 140,
        height: 56,
        zIndex: 1,
      },
      {
        id: 'el-company',
        type: 'companyName',
        x: 40,
        y: 100,
        width: 360,
        height: 32,
        style: { fontSize: 22, fontWeight: 'bold', color: '#1e40af' },
        zIndex: 2,
      },
      {
        id: 'el-company-rnc',
        type: 'companyRnc',
        x: 40,
        y: 136,
        width: 360,
        height: 22,
        style: { fontSize: 11 },
        zIndex: 2,
      },
      {
        id: 'el-company-addr',
        type: 'companyAddress',
        x: 40,
        y: 160,
        width: 360,
        height: 40,
        style: { fontSize: 11 },
        zIndex: 2,
      },
      {
        id: 'el-company-phone',
        type: 'companyPhone',
        x: 40,
        y: 204,
        width: 360,
        height: 22,
        style: { fontSize: 11 },
        zIndex: 2,
      },
      {
        id: 'el-meta',
        type: 'quotationNumber',
        x: 480,
        y: 40,
        width: 280,
        height: 28,
        style: { fontSize: 18, fontWeight: 'bold', textAlign: 'right' },
        zIndex: 2,
      },
      {
        id: 'el-date',
        type: 'date',
        x: 480,
        y: 72,
        width: 280,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 2,
      },
      {
        id: 'el-validity',
        type: 'validityDays',
        x: 480,
        y: 98,
        width: 280,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 2,
      },
      {
        id: 'el-client',
        type: 'clientName',
        x: 40,
        y: 248,
        width: 400,
        height: 28,
        style: { fontSize: 14, fontWeight: 'bold' },
        zIndex: 3,
      },
      {
        id: 'el-client-rnc',
        type: 'clientRnc',
        x: 40,
        y: 280,
        width: 400,
        height: 22,
        style: { fontSize: 11 },
        zIndex: 3,
      },
      {
        id: 'el-client-addr',
        type: 'clientAddress',
        x: 40,
        y: 304,
        width: 400,
        height: 40,
        style: { fontSize: 11 },
        zIndex: 3,
      },
      {
        id: 'el-client-phone',
        type: 'clientPhone',
        x: 40,
        y: 348,
        width: 400,
        height: 22,
        style: { fontSize: 11 },
        zIndex: 3,
      },
      {
        id: 'el-client-email',
        type: 'clientEmail',
        x: 40,
        y: 372,
        width: 400,
        height: 22,
        style: { fontSize: 11 },
        zIndex: 3,
      },
      {
        id: 'el-table',
        type: 'productTable',
        x: 40,
        y: 416,
        width: 714,
        height: 280,
        zIndex: 4,
      },
      {
        id: 'el-subtotal',
        type: 'subtotal',
        x: 480,
        y: 712,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 5,
      },
      {
        id: 'el-discount',
        type: 'discount',
        x: 480,
        y: 740,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 5,
      },
      {
        id: 'el-tax',
        type: 'tax',
        x: 480,
        y: 768,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 5,
      },
      {
        id: 'el-total',
        type: 'total',
        x: 480,
        y: 800,
        width: 274,
        height: 32,
        style: { fontSize: 16, fontWeight: 'bold', textAlign: 'right', color: '#1e40af' },
        zIndex: 5,
      },
      {
        id: 'el-notes',
        type: 'notes',
        x: 40,
        y: 860,
        width: 400,
        height: 80,
        style: { fontSize: 11 },
        zIndex: 6,
      },
    ],
  };
}
