import type { QuoteTemplateDefinition, TemplateElement } from './types';
import { createDefaultTemplateDefinition } from './defaultTemplate';

export type TemplatePresetPreviewVariant =
  | 'clasica'
  | 'moderna'
  | 'compacta'
  | 'formal'
  | 'factura';

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  /** Texto corto para la miniatura */
  previewLabel: string;
  tags: string[];
  previewVariant: TemplatePresetPreviewVariant;
  definition: QuoteTemplateDefinition;
}

const PAGE = { version: 1 as const, pageWidth: 794, pageHeight: 1123 };

function el(
  partial: Omit<TemplateElement, 'id'> & { id: string }
): TemplateElement {
  return partial;
}

function createModernaDefinition(): QuoteTemplateDefinition {
  return {
    ...PAGE,
    elements: [
      el({
        id: 'm-bar',
        type: 'freeText',
        x: 0,
        y: 0,
        width: 794,
        height: 8,
        content: '',
        style: { backgroundColor: '#1e40af' },
        zIndex: 0,
      }),
      el({
        id: 'm-logo',
        type: 'companyLogo',
        x: 40,
        y: 28,
        width: 120,
        height: 48,
        zIndex: 1,
      }),
      el({
        id: 'm-company',
        type: 'companyName',
        x: 180,
        y: 32,
        width: 380,
        height: 36,
        style: { fontSize: 20, fontWeight: 'bold', color: '#0f172a' },
        zIndex: 2,
      }),
      el({
        id: 'm-company-meta',
        type: 'companyPhone',
        x: 180,
        y: 72,
        width: 380,
        height: 22,
        style: { fontSize: 10, color: '#64748b' },
        zIndex: 2,
      }),
      el({
        id: 'm-title',
        type: 'freeText',
        x: 520,
        y: 28,
        width: 234,
        height: 32,
        content: 'COTIZACIÓN',
        style: {
          fontSize: 22,
          fontWeight: 'bold',
          textAlign: 'right',
          color: '#1e40af',
        },
        zIndex: 2,
      }),
      el({
        id: 'm-num',
        type: 'quotationNumber',
        x: 520,
        y: 64,
        width: 234,
        height: 26,
        style: { fontSize: 14, textAlign: 'right' },
        zIndex: 2,
      }),
      el({
        id: 'm-date',
        type: 'date',
        x: 520,
        y: 92,
        width: 234,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 2,
      }),
      el({
        id: 'm-client-h',
        type: 'freeText',
        x: 40,
        y: 128,
        width: 200,
        height: 20,
        content: 'Datos del cliente',
        style: { fontSize: 10, fontWeight: 'bold', color: '#64748b' },
        zIndex: 3,
      }),
      el({
        id: 'm-client',
        type: 'clientName',
        x: 40,
        y: 152,
        width: 420,
        height: 28,
        style: { fontSize: 14, fontWeight: 'bold' },
        zIndex: 3,
      }),
      el({
        id: 'm-client-rnc',
        type: 'clientRnc',
        x: 40,
        y: 184,
        width: 420,
        height: 20,
        style: { fontSize: 11 },
        zIndex: 3,
      }),
      el({
        id: 'm-client-addr',
        type: 'clientAddress',
        x: 40,
        y: 208,
        width: 420,
        height: 36,
        style: { fontSize: 11 },
        zIndex: 3,
      }),
      el({
        id: 'm-table',
        type: 'productTable',
        x: 40,
        y: 260,
        width: 714,
        height: 300,
        zIndex: 4,
      }),
      el({
        id: 'm-sub',
        type: 'subtotal',
        x: 480,
        y: 580,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 5,
      }),
      el({
        id: 'm-tax',
        type: 'tax',
        x: 480,
        y: 608,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 5,
      }),
      el({
        id: 'm-total',
        type: 'total',
        x: 480,
        y: 640,
        width: 274,
        height: 36,
        style: { fontSize: 18, fontWeight: 'bold', textAlign: 'right', color: '#1e40af' },
        zIndex: 5,
      }),
      el({
        id: 'm-notes',
        type: 'notes',
        x: 40,
        y: 700,
        width: 400,
        height: 72,
        style: { fontSize: 11 },
        zIndex: 6,
      }),
    ],
  };
}

function createCompactaDefinition(): QuoteTemplateDefinition {
  return {
    ...PAGE,
    elements: [
      el({
        id: 'c-company',
        type: 'companyName',
        x: 40,
        y: 32,
        width: 360,
        height: 28,
        style: { fontSize: 16, fontWeight: 'bold' },
        zIndex: 1,
      }),
      el({
        id: 'c-meta',
        type: 'quotationNumber',
        x: 480,
        y: 32,
        width: 274,
        height: 24,
        style: { fontSize: 14, fontWeight: 'bold', textAlign: 'right' },
        zIndex: 1,
      }),
      el({
        id: 'c-date',
        type: 'date',
        x: 480,
        y: 58,
        width: 274,
        height: 20,
        style: { fontSize: 10, textAlign: 'right' },
        zIndex: 1,
      }),
      el({
        id: 'c-client',
        type: 'clientName',
        x: 40,
        y: 72,
        width: 300,
        height: 22,
        style: { fontSize: 12, fontWeight: 'bold' },
        zIndex: 2,
      }),
      el({
        id: 'c-rnc',
        type: 'clientRnc',
        x: 40,
        y: 96,
        width: 300,
        height: 18,
        style: { fontSize: 10 },
        zIndex: 2,
      }),
      el({
        id: 'c-table',
        type: 'productTable',
        x: 40,
        y: 124,
        width: 714,
        height: 420,
        zIndex: 3,
      }),
      el({
        id: 'c-sub',
        type: 'subtotal',
        x: 480,
        y: 560,
        width: 274,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 4,
      }),
      el({
        id: 'c-tax',
        type: 'tax',
        x: 480,
        y: 584,
        width: 274,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 4,
      }),
      el({
        id: 'c-total',
        type: 'total',
        x: 480,
        y: 612,
        width: 274,
        height: 28,
        style: { fontSize: 14, fontWeight: 'bold', textAlign: 'right' },
        zIndex: 4,
      }),
    ],
  };
}

function createFormalDefinition(): QuoteTemplateDefinition {
  return {
    ...PAGE,
    elements: [
      el({
        id: 'f-title',
        type: 'freeText',
        x: 40,
        y: 40,
        width: 714,
        height: 40,
        content: 'PROPUESTA COMERCIAL',
        style: {
          fontSize: 24,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#0f172a',
        },
        zIndex: 1,
      }),
      el({
        id: 'f-line',
        type: 'freeText',
        x: 120,
        y: 84,
        width: 554,
        height: 2,
        content: '',
        style: { backgroundColor: '#cbd5e1' },
        zIndex: 1,
      }),
      el({
        id: 'f-logo',
        type: 'companyLogo',
        x: 327,
        y: 100,
        width: 140,
        height: 56,
        zIndex: 2,
      }),
      el({
        id: 'f-company',
        type: 'companyName',
        x: 40,
        y: 168,
        width: 714,
        height: 28,
        style: { fontSize: 14, fontWeight: 'bold', textAlign: 'center' },
        zIndex: 2,
      }),
      el({
        id: 'f-company-rnc',
        type: 'companyRnc',
        x: 40,
        y: 198,
        width: 714,
        height: 20,
        style: { fontSize: 11, textAlign: 'center' },
        zIndex: 2,
      }),
      el({
        id: 'f-num',
        type: 'quotationNumber',
        x: 40,
        y: 232,
        width: 350,
        height: 24,
        style: { fontSize: 12 },
        zIndex: 3,
      }),
      el({
        id: 'f-date',
        type: 'date',
        x: 404,
        y: 232,
        width: 350,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 3,
      }),
      el({
        id: 'f-valid',
        type: 'validityDays',
        x: 404,
        y: 258,
        width: 350,
        height: 20,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 3,
      }),
      el({
        id: 'f-client-label',
        type: 'freeText',
        x: 40,
        y: 296,
        width: 714,
        height: 20,
        content: 'Presentado a:',
        style: { fontSize: 10, fontWeight: 'bold', color: '#64748b' },
        zIndex: 4,
      }),
      el({
        id: 'f-client',
        type: 'clientName',
        x: 40,
        y: 318,
        width: 714,
        height: 28,
        style: { fontSize: 14, fontWeight: 'bold' },
        zIndex: 4,
      }),
      el({
        id: 'f-client-rnc',
        type: 'clientRnc',
        x: 40,
        y: 350,
        width: 350,
        height: 20,
        style: { fontSize: 11 },
        zIndex: 4,
      }),
      el({
        id: 'f-client-phone',
        type: 'clientPhone',
        x: 404,
        y: 350,
        width: 350,
        height: 20,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 4,
      }),
      el({
        id: 'f-table',
        type: 'productTable',
        x: 40,
        y: 388,
        width: 714,
        height: 280,
        zIndex: 5,
      }),
      el({
        id: 'f-sub',
        type: 'subtotal',
        x: 480,
        y: 688,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 6,
      }),
      el({
        id: 'f-tax',
        type: 'tax',
        x: 480,
        y: 716,
        width: 274,
        height: 24,
        style: { fontSize: 12, textAlign: 'right' },
        zIndex: 6,
      }),
      el({
        id: 'f-total',
        type: 'total',
        x: 480,
        y: 748,
        width: 274,
        height: 32,
        style: { fontSize: 16, fontWeight: 'bold', textAlign: 'right' },
        zIndex: 6,
      }),
      el({
        id: 'f-sig',
        type: 'signature',
        x: 40,
        y: 820,
        width: 400,
        height: 28,
        style: { fontSize: 11 },
        zIndex: 7,
      }),
      el({
        id: 'f-notes',
        type: 'notes',
        x: 40,
        y: 860,
        width: 714,
        height: 64,
        style: { fontSize: 10 },
        zIndex: 7,
      }),
    ],
  };
}

function createFacturaDefinition(): QuoteTemplateDefinition {
  return {
    ...PAGE,
    elements: [
      el({
        id: 'i-title',
        type: 'freeText',
        x: 40,
        y: 36,
        width: 300,
        height: 36,
        content: 'FACTURA',
        style: { fontSize: 26, fontWeight: 'bold', color: '#1e40af' },
        zIndex: 1,
      }),
      el({
        id: 'i-ncf',
        type: 'freeText',
        x: 40,
        y: 76,
        width: 400,
        height: 28,
        content: 'NCF: {{fiscal_number}}',
        style: { fontSize: 14, fontWeight: 'bold' },
        zIndex: 1,
      }),
      el({
        id: 'i-estado',
        type: 'freeText',
        x: 40,
        y: 108,
        width: 280,
        height: 22,
        content: 'Estado: {{estado}}',
        style: { fontSize: 11 },
        zIndex: 1,
      }),
      el({
        id: 'i-logo',
        type: 'companyLogo',
        x: 580,
        y: 36,
        width: 174,
        height: 64,
        zIndex: 2,
      }),
      el({
        id: 'i-company',
        type: 'companyName',
        x: 400,
        y: 108,
        width: 354,
        height: 28,
        style: { fontSize: 13, fontWeight: 'bold', textAlign: 'right' },
        zIndex: 2,
      }),
      el({
        id: 'i-company-rnc',
        type: 'companyRnc',
        x: 400,
        y: 138,
        width: 354,
        height: 20,
        style: { fontSize: 10, textAlign: 'right' },
        zIndex: 2,
      }),
      el({
        id: 'i-date',
        type: 'date',
        x: 480,
        y: 168,
        width: 274,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 2,
      }),
      el({
        id: 'i-client-h',
        type: 'freeText',
        x: 40,
        y: 200,
        width: 200,
        height: 18,
        content: 'Cliente',
        style: { fontSize: 10, fontWeight: 'bold', color: '#64748b' },
        zIndex: 3,
      }),
      el({
        id: 'i-client',
        type: 'clientName',
        x: 40,
        y: 222,
        width: 420,
        height: 28,
        style: { fontSize: 14, fontWeight: 'bold' },
        zIndex: 3,
      }),
      el({
        id: 'i-client-rnc',
        type: 'clientRnc',
        x: 40,
        y: 254,
        width: 420,
        height: 20,
        style: { fontSize: 11 },
        zIndex: 3,
      }),
      el({
        id: 'i-client-addr',
        type: 'clientAddress',
        x: 40,
        y: 278,
        width: 420,
        height: 36,
        style: { fontSize: 11 },
        zIndex: 3,
      }),
      el({
        id: 'i-table',
        type: 'productTable',
        x: 40,
        y: 328,
        width: 714,
        height: 300,
        zIndex: 4,
      }),
      el({
        id: 'i-disc',
        type: 'discount',
        x: 480,
        y: 648,
        width: 274,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 5,
      }),
      el({
        id: 'i-sub',
        type: 'subtotal',
        x: 480,
        y: 674,
        width: 274,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 5,
      }),
      el({
        id: 'i-tax',
        type: 'tax',
        x: 480,
        y: 700,
        width: 274,
        height: 22,
        style: { fontSize: 11, textAlign: 'right' },
        zIndex: 5,
      }),
      el({
        id: 'i-total',
        type: 'total',
        x: 480,
        y: 730,
        width: 274,
        height: 36,
        style: { fontSize: 18, fontWeight: 'bold', textAlign: 'right', color: '#1e40af' },
        zIndex: 5,
      }),
      el({
        id: 'i-pago',
        type: 'freeText',
        x: 40,
        y: 790,
        width: 400,
        height: 22,
        content: 'Forma de pago: {{forma_pago}}',
        style: { fontSize: 11 },
        zIndex: 6,
      }),
      el({
        id: 'i-notes',
        type: 'notes',
        x: 40,
        y: 820,
        width: 714,
        height: 64,
        style: { fontSize: 10 },
        zIndex: 6,
      }),
    ],
  };
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: 'clasica',
    name: 'Clásica',
    previewLabel: 'Logo + cliente completo',
    description:
      'La plantilla recomendada: logo, empresa, cliente con RNC y dirección, tabla de ítems y totales. Sirve para cotizaciones y facturas.',
    tags: ['Cotización', 'Factura', 'Recomendada'],
    previewVariant: 'clasica',
    definition: createDefaultTemplateDefinition(),
  },
  {
    id: 'moderna',
    name: 'Moderna',
    previewLabel: 'Encabezado azul',
    description:
      'Diseño actual con barra superior, título “Cotización” destacado y bloques bien separados. Ideal para propuestas comerciales.',
    tags: ['Cotización'],
    previewVariant: 'moderna',
    definition: createModernaDefinition(),
  },
  {
    id: 'compacta',
    name: 'Compacta',
    previewLabel: 'Menos espacio, más ítems',
    description:
      'Ocupa poco espacio en la parte superior para dejar más filas en la tabla. Útil cuando tienes muchos productos o servicios.',
    tags: ['Cotización', 'Muchos ítems'],
    previewVariant: 'compacta',
    definition: createCompactaDefinition(),
  },
  {
    id: 'formal',
    name: 'Formal',
    previewLabel: 'Centrada y elegante',
    description:
      'Título centrado “Propuesta comercial”, logo al medio y presentación sobria. Transmite seriedad ante clientes corporativos.',
    tags: ['Cotización'],
    previewVariant: 'formal',
    definition: createFormalDefinition(),
  },
  {
    id: 'factura',
    name: 'Factura fiscal',
    previewLabel: 'NCF y estado',
    description:
      'Pensada para facturas: título FACTURA, número fiscal (NCF), estado, descuento y forma de pago. También funciona al exportar cotizaciones.',
    tags: ['Factura', 'NCF'],
    previewVariant: 'factura',
    definition: createFacturaDefinition(),
  },
];

export function getTemplatePresetById(id: string): TemplatePreset | undefined {
  return TEMPLATE_PRESETS.find((p) => p.id === id);
}
